server:
  port: 9006

spring:
  application:
    name: user-service-provide

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

    config:
      label: master   #分支名称
      name: user      #配置文件名称
      profile: dev    #读取后缀
      uri: config-service-2021  #配置中心地址



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yuxi.springcloud.api.entity
  configuration:
    #驼峰转换
    map-underscore-to-camel-case: true

